# Use only ascii symbols in comments.

Layout/LineLength:
  Max: 130 # 1行あたりの文字数チェック

Metrics/AbcSize:
  Enabled: true
  Max: 45 # ABCサイズチェック

Metrics/MethodLength:
  CountComments: true # コメントも行数に数えるか
  Max: 30 # メソッド内に何行書けるか

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: true

Style/AsciiComments:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - config.ru
    - Gemfile
    - Rakefile
    - bin/*
    - config/**/*
    - 'vendor/**/*'
    - spec/**/*
