version: '3'
services:
  lodqa-bs:
    build: https://github.com/lodqa/lodqa_bs.git

  lodqa_email_agent:
    build: .
    volumes:
      - .:/usr/src/myapp
    env_file:
      - .env
    depends_on:
      - lodqa-bs
